title: Kevin Samuel
email: contact@kevinnlsamuel.com
description: >-
  A graduate of English literature with an inclination
  for working with languages in content, classrooms and code.
baseurl: "/"
url: "https://resume.kevinnlsamuel.com"
twitter_username: kevinnlsamuel
github_username:  kevinnls

